name: Build Android AAB

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kode
      uses: actions/checkout@v4

    - name: Siapkan Mesin Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Modul Pembangun
      run: npm install

    - name: Tambahkan Kerangka Android
      run: |
        npx cap add android
        npx cap copy

    - name: Kompilasi Menjadi AAB (Release)
      run: |
        cd android
        ./gradlew bundleRelease

    - name: Simpan Hasil AAB
      uses: actions/upload-artifact@v4
      with:
        name: LaporanMandiri-AAB
        path: android/app/build/outputs/bundle/release/app-release.aab
