name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kode
      uses: actions/checkout@v4

    - name: Siapkan Mesin Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Modul Pembangun
      run: npm install

    - name: Tambahkan Kerangka Android
      run: |
        npx cap add android
        npx cap copy

    - name: Kompilasi Menjadi APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Simpan Hasil APK
      uses: actions/upload-artifact@v4
      with:
        name: LaporanMandiri-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
